# Generated by Django 2.2.4 on 2019-08-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('accesstoken', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Login',
            },
        ),
    ]
